### ISSUE TITLE
Eventtickettypes-luokka

### ISSUE THREAD

**Issue by miljahai** [miljahai/TicketGuru#18]
https://github.com/users/miljahai/projects/1/views/1?pane=issue&itemId=19492181

**Comment by jpsirvio** [comment]
Odottaa tickettypes-luokkaa, https://github.com/users/miljahai/projects/1/views/1?pane=issue&itemId=19891928

**Comment by jpsirvio** [comment]
Ei tarvita omana luokkanaan. Sen sijaan toteutettu @ManyToMany relaatio EventRecord ja TicketType -tauluihin.

**Comment by jpsirvio** [comment]
Done. Testattava.
