### ISSUE TITLE
Käyttäjäroolien laatiminen

### ISSUE THREAD

**Issue by jpsirvio** [miljahai/TicketGuru#5]

**Comment by jpsirvio** [comment]
Ehdotus  käyttäjärooleiksi:
- Tilaaja == Asiakkaan tietohallinto, joka tilaa järjestelmän, vähän hähmäinen
- Myyjä == Asiakkaan henkilö, joka toimii asiakasrajapinnassa ja konkreettisesti myy lippuja ja syöttää myyntitapahtumia sovellukseen
- Tapahtumanjärjestäjä == Asiakkaan henkilö, joka syöttää tapahtumia ja niiden lipputyyppejä sovellukseen
- Sovelluskehittäjä == Me. Vähän hassu rooli, mutta jotain piti keksiä käyttäjätarinoihin.

Käyttäjätarina-draftit on kirjoitettu näillä, mutta muutetaan, jos keksitään parempia.

**Comment by Heli-DL** [comment]
Hyviä rooleja. Voisiko tapahtumanjärjestäjän korvata esim. palveluntarjoajalla tai jollain paremmalla termillä, koska tehtävän annon mukaan lipputoimisto syöttää itse tapahtumat, mutta tapahtumanjärjestäjä kuulostaa enemmän ulkopuoliselta taholta. 

Asiakas voisi olla vielä yksi rooli, koska se oli mainittu tarinoissa.
